apiVersion: v1
kind: Pod
metadata: 
  name: nodehelloworld.com
  labels: 
    app: helloworld
spec: 
  containers:
  - name: k8s-demo
    image: tanbery/k8s-demo #dockerhubID/Repo
    ports: 
    - name: nodejs-port 
      containerPort: 3000