apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: rng
  name: rng
  namespace: default
spec:
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - image: dockercoins/rng:v0.1
        imagePullPolicy: IfNotPresent
        name: rng
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        # livenessProbe:
        #   exec:
        #     command: ["redis-cli", "ping"]
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 10
        #   periodSeconds: 1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
