apiVersion: v1
kind: Pod
metadata: 
  name: app-env
  labels: 
    app: helloworld
spec: 
  containers:
  - name: app-env
    image: tanbery/app_env #dockerhubID/Repo
    ports: 
    - name: nodejs-port 
      containerPort: 3000