apiVersion: v1
kind: Pod
metadata: 
  name: app-env
  labels: 
    app: hello-node-app
spec: 
  containers:
  - name: app-env
    image: tanbery/hello-node-app #dockerhubID/Repo
    ports: 
    - name: nodejs-port 
      containerPort: 3000