apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-app-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: app-env
        image: tanbery/app_env
        ports:
        - name: nodejs-port
          containerPort: 3000