apiVersion: v1
kind: ReplicationController
metadata:
  name: app-env-repl-controller
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: app-env
        image: tanbery/app_env
        ports:
        - name: nodejs-port
          containerPort: 3000
